language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
install:
  - "pip install -q -r requirements.txt --use-mirrors"
  - "pip install -q -r test_pmort/requirements.txt --use-mirrors"
  - "pip install -q Jinja2
script:
  - PYTHONPATH='.' scripts/render_templates conf
  - python setup.py install
  - nosetests
