#!/usr/bin/env python
#
# Copyright (C) 2013 by Alex Brandt <alunduil@alunduil.com>
#
# pmort is freely distributable under the terms of an MIT-style license.
# See COPYING or http://www.opensource.org/licenses/mit-license.php.

import argparse
import os

from jinja2 import Environment, FileSystemLoader

from pmort.parameters import PARAMETERS
from pmort import information

def grouped_parameters():
    groups = {}

    for name, parameter in PARAMETERS.parameters.items():
        group = parameter['group']

        if group not in groups:
            groups[group] = {}

        groups[group][name] = parameter

    return groups

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument(
            'filepaths',
            metavar = 'FILE',
            nargs = '+',
            help = 'Files to render from templates.'
            )
    arguments = parser.parse_args()

    for filepath in arguments.filepaths:
        directory, filename = os.path.split(filepath)

        env = Environment(loader = FileSystemLoader(directory))
        template = env.get_template(filename)

        with open(os.path.join(directory, filename.replace('.jinja', '')), 'w') as fh:
            fh.write(template.render(
                PARAMETERS = PARAMETERS,
                information = information,
                grouped_parameters = grouped_parameters()
                ))
            fh.flush()

if __name__ == '__main__':
    main()
